package com.example.androidmovelist;

public final class CharacterData {
	public static final String[] characterNames = { 
        "Ragna", 
        "Jin", 
        "Noel",
        "Rachel",
        "Taokaka",
        "Tager",
        "Litchi",
        "Arakune",
        "Bang",
        "Carl",
        "Hakumen",
        "Tsubaki",
        "Hazama",
        "Makoto",
        "Valkenhein",
        "Platnium",
        "Relius",
        "Amane",
        "Bullet",
        "Azreal",
        "Nu-13",
        "Mu-12",
        "Izayoi",
        "Kagura",
        "Terumi",
        "Kokonoe"};
	public static final int[] iconIds =	{
		R.drawable.icon_ragna,
		R.drawable.icon_jin,
		R.drawable.icon_noel,
		R.drawable.icon_rachel,
		R.drawable.icon_tao,
		R.drawable.icon_tager,
		R.drawable.icon_litchi,
		R.drawable.icon_arakune,
		R.drawable.icon_bang,
		R.drawable.icon_carl,
		R.drawable.icon_hakumen,
		R.drawable.icon_tsubaki,
		R.drawable.icon_hazama,
		R.drawable.icon_makoto,
		R.drawable.icon_valkenhayn,
		R.drawable.icon_platnium,
		R.drawable.icon_relius,
		R.drawable.icon_amane,
		R.drawable.icon_bullet,
		R.drawable.icon_azael,
		R.drawable.icon_v13,
		R.drawable.icon_mu12,
		R.drawable.icon_izayoi,
		R.drawable.icon_kagura,
		R.drawable.icon_terumi,
		R.drawable.icon_kokonoe};
	
	public static final int[] styleishMovesIds =	{
		R.drawable.ragna_styleish,
		R.drawable.jin_styleish,
		R.drawable.noel_stylish,
		R.drawable.rachel_stylish,
		R.drawable.taokaka_stylish,
		R.drawable.tager_stylish,
		R.drawable.litchi_stylish,
		R.drawable.arakune_stylish,
		R.drawable.bang_stylish,
		R.drawable.carl_stylish,
		R.drawable.hakumen_stylish,
		R.drawable.tsubaki_stylish,
		R.drawable.hazama_stylish,
		R.drawable.makoto_stylish,
		R.drawable.valkenhayn_stylish,
		R.drawable.platinum_stylish,
		R.drawable.relius_stylish,
		R.drawable.amane_stylish,
		R.drawable.bullet_stylish,
		R.drawable.azrael_stylish,
		R.drawable.nu13_stylish,
		R.drawable.mu12_stylish,
		R.drawable.izayoi_stylish,
		R.drawable.kagura_stylish,
		R.drawable.terumi_stylish,
		R.drawable.kokonoe_stylish};
	
	public static final int[] technicalMovesIds =	{
		R.drawable.ragna_technical,
		R.drawable.jin_technical,
		R.drawable.noel_technical,
		R.drawable.rachel_technical,
		R.drawable.taokaka_technical,
		R.drawable.tager_technical,
		R.drawable.litchi_technical,
		R.drawable.arakune_technical,
		R.drawable.bang_technical,
		R.drawable.carl_technical,
		R.drawable.hakumen_technical,
		R.drawable.tsubaki_technical,
		R.drawable.hazama_technical,
		R.drawable.makoto_technical,
		R.drawable.valkenhayn_technical,
		R.drawable.platinum_technical,
		R.drawable.relius_technical,
		R.drawable.amane_technical,
		R.drawable.bullet_technical,
		R.drawable.azrael_technical,
		R.drawable.nu13_technical,
		R.drawable.mu12_technical,
		R.drawable.izayoi_technical,
		R.drawable.kagura_technical,
		R.drawable.terumi_technical,
		R.drawable.kokonoe_technical};
	
	private CharacterData(){}
}
