package com.example.streetfighter4movelist;

import com.example.streetfighter4movelist.R;

public final class CharacterData {
	public static final String[] characterNames = { 
		"Abel",
		"Adon",
		"Akuma",
		"Balrog",
		"Bison",
		"Blanka",
		"Cammy",
		"Chunli",
		"Cody",
		"Dan",
		"Deejay",
		"Dhalsim",
		"Dudley",
		"Ehonda",
		"Elfuerte",
		"Feilong",
		"Gen",
		"Gouken",
		"Guile",
		"Guy",
		"Hakan",
		"Ibuki",
		"Juri",
		"Ken",
		"Makoto",
		"Rose",
		"Rufus",
		"Ryu",
		"Sagat",
		"Sakura",
		"Seth",
		"Thawk",
		"Vega",
		"Viper",
		"Zangief",
		"Yang",
		"Yun",
		"Evil Ryu",
		"Oni"};
	
	public static int xbal = R.drawable.ic_launcher;
	
	public static final int[] iconIds =	{
		R.drawable.icon_abel,
		R.drawable.icon_adon,
		R.drawable.icon_akuma,
		R.drawable.icon_balrog,
		R.drawable.icon_bison,
		R.drawable.icon_blanka,
		R.drawable.icon_cammy,
		R.drawable.icon_chunli,
		R.drawable.icon_cody,
		R.drawable.icon_dan,
		R.drawable.icon_deejay,
		R.drawable.icon_dhalsim,
		R.drawable.icon_dudley,
		R.drawable.icon_ehonda,
		R.drawable.icon_elfuerte,
		R.drawable.icon_feilong,
		R.drawable.icon_gen,
		R.drawable.icon_gouken,
		R.drawable.icon_guile,
		R.drawable.icon_guy,
		R.drawable.icon_hakan,
		R.drawable.icon_ibuki,
		R.drawable.icon_juri,
		R.drawable.icon_ken,
		R.drawable.icon_makoto,
		R.drawable.icon_rose,
		R.drawable.icon_rufus,
		R.drawable.icon_ryu,
		R.drawable.icon_sagat,
		R.drawable.icon_sakura,
		R.drawable.icon_seth,
		R.drawable.icon_thawk,
		R.drawable.icon_vega,
		R.drawable.icon_viper,
		R.drawable.icon_zangief,
		R.drawable.icon_yang,
		R.drawable.icon_yun,
		R.drawable.icon_eryu,
		R.drawable.icon_oni};
	
	public static final int[] moveIds =	{
		R.drawable.abel,
		R.drawable.adon,
		R.drawable.akuma,
		R.drawable.balrog,
		R.drawable.bison,
		R.drawable.blanka,
		R.drawable.cammy,
		R.drawable.chunli,
		R.drawable.cody,
		R.drawable.dan,
		R.drawable.deejay,
		R.drawable.dhalsim,
		R.drawable.dudley,
		R.drawable.ehonda,
		R.drawable.elfuerte,
		R.drawable.feilong,
		R.drawable.gen,
		R.drawable.goken,
		R.drawable.guile,
		R.drawable.guy,
		R.drawable.hakan,
		R.drawable.ibuki,
		R.drawable.juri,
		R.drawable.ken,
		R.drawable.makoto,
		R.drawable.rose,
		R.drawable.rufus,
		R.drawable.ryu,
		R.drawable.sagat,
		R.drawable.sakura,
		R.drawable.seth,
		R.drawable.thawk,
		R.drawable.vega,
		R.drawable.viper,
		R.drawable.zangief,
		R.drawable.yang,
		R.drawable.yun,
		R.drawable.evilryu,
		R.drawable.oni,};
	
	private CharacterData(){}
}